apiVersion: batch/v1
kind: Job
metadata:
  name: orders-migration
  namespace: order-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ordersystem-api:v6
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Running database migration..."
              dotnet Order.Api.dll
          envFrom:
            - configMapRef:
                name: orders-config
            - secretRef:
                name: orders-secret
          env:
            - name: RunMode
              value: "migration"