apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: order-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: ordersystem-api:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
     
          envFrom:
            - configMapRef:
                name: orders-config
            - secretRef:
                name: orders-secret
          env:
            - name: DisableWorkers
              value: "true"
            - name: RunMode
              value: "api"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10