apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: order-system
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"